name: confluent-kafka
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - ca-certificates=2019.11.28
  - certifi=2019.11.28
  - cyrus-sasl=2.1.27
  - gettext=0.19.8.1
  - krb5=1.16.4
  - libedit=3.1.20170329
  - libffi=3.2.1
  - libgcrypt=1.8.4
  - libgpg-error=1.36
  - libgsasl=1.8.0
  - libntlm=1.4
  - librdkafka=1.3.0
  - lz4-c=1.8.3
  - ncurses=6.1
  - openssl=1.1.1d
  - pip=19.3.1
  - python=3.8.0
  - readline=8.0
  - setuptools=42.0.2
  - sqlite=3.30.1
  - tk=8.6.10
  - wheel=0.33.6
  - xz=5.2.4
  - zlib=1.2.11
  - pip:
    - avro-python3==1.8.2
    - chardet==3.0.4
    - confluent-kafka==1.3.0
    - fastavro==0.22.9
    - idna==2.8
    - requests==2.22.0
    - urllib3==1.25.7
